name: Pull Request Check

on: [pull_request]

env:
  JAVA_VERSION: 17 # gradleに対応するものを選ぶ
  GRADLE_VERSION: 8.2

permissions:
  pull-requests: write

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      # android lintを実行
      - name: Run Android Lint
        run: ./gradlew lint

      - name: Comment via reviewdog
        run: |
          cat app/build/reports/android-lint/lintResults.sarif \
            | reviewdog -f=sarif -reporter=github-pr-check -filter-mode=nofilter -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}