name: Pull Request Check

on: [pull_request]

env:
  JAVA_VERSION: 17 # gradleに対応するものを選ぶ
  GRADLE_VERSION: 8.2

permissions:
  pull-requests: write

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      # setup
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      # android lintを実行
      - name: Android Lint
        id: android-lint
        run: ./gradlew lint
      # report
      - name: Comment PR via reviewdog (with debug)
        if: always()
        run: |
          FILE=./app/build/reports/android-lint/lintResults.sarif
          if [ -f "$FILE" ]; then
            cat "$FILE" | reviewdog -f=sarif -reporter=github-pr-review -filter-mode=added -tee
          fi
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Comment PR by reviewdog
#        if: always()
#        run: |
#          find ./*/build/reports/android-lint/lintResults.sarif \
#            -type f \
#            -exec sh -c "cat {} | reviewdog -f=sarif -reporter=github-pr-review" \;
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}